# Usa una imagen base con Elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.0

# Expone el puerto 9200 para Elasticsearch
EXPOSE 9200

# Ejecuta Elasticsearch
CMD ["elasticsearch"]
